[package]
name = "rocket-cms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-watch = "8.1.2"
rocket = "0.5.0-rc.2"
rocket_contrib = "0.4.11"
